# Starter pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Sub4(1371234f-bae7-4c6e-9e99-6966c705552c)'
    subscriptionId: '1371234f-bae7-4c6e-9e99-6966c705552c'
    action: 'Create Or Update Resource Group'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/tsaraspanos/AzureRMPipeline-Repo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName  tsarastem'
    deploymentMode: 'Incremental'
    deploymentName: 'tsarasAzureDep'